'use client';

import { useState } from 'react';

export default function StaffPortal() {
  const [checkedIn, setCheckedIn] = useState(true);
  const [completed, setCompleted] = useState<string[]>(['aanya']);
  const schedule = [
    { id: 'aanya', time: '10:00', name: 'Aanya Mehta', service: 'Global colour', duration: '2h', status: 'In service', note: 'Warm mocha · shade 5.3' },
    { id: 'neha', time: '12:30', name: 'Neha Kapoor', service: 'Restorative hair spa', duration: '1h 15m', status: 'Confirmed', note: 'Sensitive scalp · low heat' },
    { id: 'mira', time: '02:30', name: 'Mira Jain', service: 'Balayage consultation', duration: '45m', status: 'Confirmed', note: 'First colour consultation' },
    { id: 'devika', time: '04:00', name: 'Devika Mehra', service: 'Global colour', duration: '2h', status: 'Confirmed', note: 'Cover roots · formula in history' },
  ];
  return <main className="staff-portal-shell"><aside className="staff-sidebar"><a className="wordmark" href="/"><span>CUTZ</span><i>&</i><span>BANGS</span></a><nav><a className="active" href="#day"><span>MY</span>My day</a><a href="#calendar"><span>CA</span>Calendar</a><a href="#customers"><span>CU</span>Customers</a><a href="#commission"><span>₹</span>Commission</a><a href="#notifications"><span>NO</span>Notifications<b>3</b></a></nav><div className="staff-side-profile"><span>RS</span><div><strong>Riya Sen</strong><small>Creative colourist</small></div></div></aside><section className="staff-main"><header><div><p className="eyebrow">Saturday, 22 August</p><h1>Good morning, Riya.</h1><p>You have 4 appointments and a comfortable 45-minute break today.</p></div><div className={`checkin-card ${checkedIn?'active':''}`}><span>{checkedIn?'✓':'○'}</span><p><small>{checkedIn?'Checked in':'Not checked in'}</small><strong>{checkedIn?'9:46 AM':'—'}</strong></p><button onClick={()=>setCheckedIn(!checkedIn)}>{checkedIn?'Check out':'Check in'}</button></div></header><div className="staff-kpis"><article><span>CA</span><small>Appointments</small><strong>4</strong><p>6h of service time</p></article><article><span>₹</span><small>Today’s sales</small><strong>₹8,296</strong><p>₹1,244 est. commission</p></article><article><span>CL</span><small>Clients seen</small><strong>{completed.length}</strong><p>{4-completed.length} remaining</p></article></div><section className="staff-schedule" id="day"><div className="section-heading"><div><p className="eyebrow">Your schedule</p><h2>Today, at a glance</h2></div><button>Full calendar →</button></div><div className="staff-timeline">{schedule.map((item,index)=>{const done=completed.includes(item.id);return <article className={done?'done':''} key={item.id}><time>{item.time}<small>{index<2?'AM':'PM'}</small></time><span className="staff-line"><i/></span><div className="staff-appointment"><header><span>{item.name.split(' ').map(word=>word[0]).join('')}</span><div><h3>{item.name}</h3><p>{item.service} · {item.duration}</p></div><em>{done?'Completed':item.status}</em></header><div className="client-note"><span>✦</span><p><small>Client note</small>{item.note}</p></div><footer><button>View history</button><button>Message</button><button className="primary" onClick={()=>setCompleted(current=>done?current.filter(id=>id!==item.id):[...current,item.id])}>{done?'Reopen':'Start service'}</button></footer></div></article>})}</div></section></section></main>;
}
