export default function CustomerPortal() {
  return <main className="portal-shell customer-portal">
    <header className="portal-header"><a className="wordmark" href="/"><span>CUTZ</span><i>&</i><span>BANGS</span></a><nav><a className="active" href="#overview">Overview</a><a href="#appointments">Appointments</a><a href="#history">History</a><a href="#invoices">Invoices</a></nav><div className="portal-profile"><span>AM</span><div><strong>Aanya</strong><small>VIP member</small></div></div></header>
    <div className="portal-content" id="overview"><section className="portal-welcome"><div><p className="eyebrow">Saturday, 22 August</p><h1>Hey Aanya,<br/><em>good hair day ahead.</em></h1><p>Your colour appointment is later today. We’ve kept everything ready.</p></div><div className="portal-orbit"><span>AM</span><i className="orbit-one">✦</i><i className="orbit-two">✦</i></div></section>
      <div className="portal-grid"><article className="upcoming-card" id="appointments"><div className="upcoming-date"><span>22</span><small>AUG<br/>SAT</small></div><div><p className="eyebrow">Up next · Today</p><h2>Global colour ritual</h2><p>4:30 PM · 2 hours · with Riya Sen</p><div><button>Get directions</button><button>Reschedule</button></div></div><span className="confirmed-pill">✓ Confirmed</span></article><article className="portal-membership"><p className="eyebrow">The Regular</p><h2>₹620</h2><span>credit remaining</span><div><i><b style={{width:'12%'}}/></i><small>₹4,380 used of ₹5,000</small></div><a href="#history">View ledger →</a></article></div>
      <section className="portal-history" id="history"><div className="section-heading"><div><p className="eyebrow">Your history</p><h2>Looks we’ve created together</h2></div><a className="text-link" href="/book">Book again <span>↗</span></a></div><div className="history-timeline">{[['18 Jul','Signature cut & blowdry','Arjun Khanna','₹799','Loved the soft layers'],['04 Jun','Global colour + hair spa','Riya Sen','₹3,798','Warm mocha · shade 5.3'],['12 Apr','Skin reset facial','Meher Malik','₹1,499','Hydration-focused'],['25 Feb','Signature cut','Arjun Khanna','₹799','Keep length at the front']].map(([date,service,staff,amount,note],index)=><article key={date}><span className="timeline-mark">{index===0?'✦':index+1}</span><time>{date}<small>2026</small></time><div><strong>{service}</strong><span>{staff}</span><em>“{note}”</em></div><strong>{amount}</strong><button>Book again</button></article>)}</div></section>
      <section className="invoice-strip" id="invoices"><div><p className="eyebrow">Receipts & invoices</p><h2>Everything in one place.</h2></div><div>{[['CB-1036','18 Jul 2026','₹799'],['CB-0988','04 Jun 2026','₹3,798'],['CB-0912','12 Apr 2026','₹1,499']].map(([id,date,amount])=><a key={id} href={`#${id}`}><span><strong>{id}</strong><small>{date}</small></span><b>{amount}</b><i>↓</i></a>)}</div></section>
    </div><nav className="portal-mobile-nav"><a className="active" href="#overview">Home</a><a href="#appointments">Bookings</a><a href="/book" className="mobile-book">＋</a><a href="#history">History</a><a href="#invoices">Profile</a></nav>
  </main>;
}
